linux_task:
  container:
    image: gcc:latest
  env:
    CODECOV_TOKEN: 47866546-4d0f-4b92-8359-083764e1123f
  setup_script:
    - apt-get update
    - apt-get install -y --no-install-recommends valgrind ccache clang cmake libev-dev zsh
  test_basic_script:
    - ./rebuild.sh
    - ./test.sh
  codecov_script:
    - ./rebuild.sh gcc-coverage no-display-coverage
    - bash <(curl -s https://codecov.io/bash)
  test_optimized_script:
    - ./rebuild.sh O3
    - ./test.sh
  test_optimized_valgrind_script:
    - ./rebuild.sh O2 valgrind
    - ./test.sh valgrind
  test_optimized_stalloc_stats_tracking_valgrind_script:
    - ./rebuild.sh stalloc_track_space O2 valgrind
    - ./test.sh valgrind
  test_no_eventfd_valgrind_script:
    - ./rebuild.sh no-eventfd O2
    - ./test.sh valgrind
  test_release_valgrind_script:
    - ./rebuild.sh release O2
    - ./test.sh valgrind

osx_task:
  osx_instance:
    image: mojave-xcode-10.1
  setup_script:
    - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
    - brew install ccache libev zsh cmake
  test_basic_script:
    - ./rebuild.sh
    - ./test.sh
  test_optimized_script:
    - ./rebuild.sh O3
    - ./test.sh
  test_sanitized_script:
    - ./rebuild.sh O2 sanitize-address
    - ./test.sh
freebsd_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  setup_script: pkg install -y gmake cmake ccache libev valgrind zsh
  test_basic_script:
    - ./rebuild.sh
    - ./test.sh
  test_optimized_script:
    - ./rebuild.sh O3
    - ./test.sh
  test_sanitized_script:
    - ./rebuild.sh O2 stalloc_track_space valgrind
    - ./test.sh valgrind
