archlinux_task:
  container:
    image: archlinux:latest
  env:
    CODECOV_TOKEN: 47866546-4d0f-4b92-8359-083764e1123f
  setup_script:
    - pacman -Syu --noconfirm
    - pacman -Sy --noconfirm base-devel git gcc valgrind clang ccache cmake libev zsh ruby lua luarocks openssl c-ares pcre2 nghttp2
    - luarocks install luacov
    - luarocks install cluacov
    - luarocks install luacov-multiple
    - luarocks install luacheck
  test_basic_script:
    - ./rebuild.rb
    - ./test.sh --color
  test_optimized_script:
    - ./rebuild.rb O3
    - ./test.sh --color
  test_optimized_valgrind_script:
    - ./rebuild.rb O2 valgrind
    - ./test.sh valgrind --color --multiplier=0.1
  test_optimized_pool_stats_tracking_valgrind_script:
    - ./rebuild.rb pool_track_space O2 valgrind
    - ./test.sh valgrind --color --multiplier=0.1
  test_no_eventfd_valgrind_script:
    - ./rebuild.rb no-eventfd O2
    - ./test.sh valgrind --color --multiplier=0.1
  test_release_valgrind_script:
    - ./rebuild.rb release O2
    - ./test.sh valgrind --color --multiplier=0.2
  codecov_script:
    - ./rebuild.rb gcc-coverage no-display-coverage
    - bash <(curl -s https://codecov.io/bash)
    - ./rebuild.rb gcc-coverage no-display-coverage nopool
    - bash <(curl -s https://codecov.io/bash)
    - ./rebuild.rb gcc-coverage no-display-coverage nothreads
    - bash <(curl -s https://codecov.io/bash)
    - ./rebuild.rb gcc-coverage no-display-coverage pool_track_space valgrind
    - bash <(curl -s https://codecov.io/bash)
    - ./rebuild.rb no-display-coverage gcc-coverage no-eventfd
    - bash <(curl -s https://codecov.io/bash)
#linux_task:
#  container:
#    image: gcc:latest
#  env:
#    CODECOV_TOKEN: 47866546-4d0f-4b92-8359-083764e1123f
#  setup_script:
#    - apt-get update
#    - apt-get install -y --no-install-recommends valgrind ccache clang cmake libev-dev zsh ruby lua5.3 liblua5.3-dev luarocks libssl-dev libc-ares-dev libpcre2-dev libnghttp2-dev
#    - luarocks install luacov
#    - luarocks install cluacov
#    - luarocks install luacov-multiple
#    - luarocks install luacheck  
osx_task:
  osx_instance:
    image: catalina-xcode
  setup_script:
    - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
    - brew update
    - brew upgrade
    - brew install ccache libev zsh ruby lua luarocks pcre2 openssl c-ares
  test_basic_script:
    - ./rebuild.rb verbose
    - ./test.sh --color
  test_optimized_script:
    - ./rebuild.rb O3
    - ./test.sh --color
#  test_sanitized_script:
#    - brew install llvm
#    - ./rebuild.rb O2 sanitize-address
#    - ./test.sh --color
freebsd_task:
  freebsd_instance:
    image: freebsd-12-1-release-amd64
  setup_script: pkg install -y c-ares gmake cmake ccache libev zsh ruby lua53 openssl pcre2 libnghttp2
  test_basic_script:
    - ruby ./rebuild.rb
    - zsh ./test.sh --color
  test_optimized_script:
    - ruby ./rebuild.rb O3
    - zsh ./test.sh --color
