#ifndef SHUTTLESOCK_BUILD_CONFIG_H
#define SHUTTLESOCK_BUILD_CONFIG_H

#define SHUTTLESOCK_MAX_WORKERS 1024
#define SHUTTLESOCK_CONFIG_DEFAULT_IPC_SEND_RETRY_DELAY  0.050
#define SHUTTLESOCK_CONFIG_DEFAULT_IPC_SEND_TIMEOUT 0.500
#define SHUTTLESOCK_CONFIG_DEFAULT_SOCKET_RECEIVE_TIMEOUT 2.000

#define SHUTTLESOCK_WATCHED_SIGNALS  {SIGTERM, SIGINT, SIGQUIT, SIGHUP, SIGCONT, SIGUSR1, SIGUSR2, SIGWINCH}

#define SHUTTLESOCK_LUA_SCRIPTS_COMPILED

/* #undef SHUTTLESOCK_DEBUG */
/* #undef SHUTTLESOCK_DEBUG_MODULE_SYSTEM */
/* #undef SHUTTLESOCK_DEBUG_STALLOC_NOPOOL */
/* #undef SHUTTLESOCK_DEBUG_NO_WORKER_THREADS */
/* #undef SHUTTLESOCK_DEBUG_VALGRIND */
/* #undef SHUTTLESOCK_DEBUG_SANITIZE */
/* #undef SHUTTLESOCK_DEBUG_LUACOV */

/* #undef SHUTTLESOCK_STALLOC_TRACK_SPACE */

/* #undef SHUTTLESOCK_BIG_ENDIAN */
#define SHUTTLESOCK_HAVE_IPV6
#define SHUTTLESOCK_HAVE_STRSIGNAL
#define SHUTTLESOCK_HAVE_EVENTFD
#define SHUTTLESOCK_USE_EVENTFD
#define SHUTTLESOCK_PTHREAD_SETNAME_STYLE_LINUX
/* #undef SHUTTLESOCK_PTHREAD_SETNAME_INCLUDE_PTRHEAD_NP */
#define SHUTTLESOCK_HAVE_TYPEOF
#define SHUTTLESOCK_USE_IO_URING
#define SHUTTLESOCK_PTR_SIZE 8
#define SHUTTLESOCK_DEFAULT_LOGLEVEL SHUSO_LOG_INFO
#endif //SHUTTLESOCK_BUILD_CONFIG_H
