
function(shuttlesock_link_pthreads)
  if(NOT DEFINED CMAKE_THREAD_LIBS_INIT)
    set(THREADS_PREFER_PTHREAD_FLAG ON)
    message(STATUS "Check if pthreads is supported")
    find_package(Threads QUIET)
    if("${CMAKE_USE_PTHREADS_INIT}")
      message(STATUS "Check if pthreads is supported - yes (${CMAKE_THREAD_LIBS_INIT})")
    else()
      message(STATUS "Check if pthreads is supported - no")
    endif()
    set(CMAKE_THREAD_LIBS_INIT "${CMAKE_THREAD_LIBS_INIT}" CACHE INTERNAL "")
    set(CMAKE_USE_PTHREADS_INIT "${CMAKE_USE_PTHREADS_INIT}" CACHE INTERNAL "")
  endif()
  if(CMAKE_THREAD_LIBS_INIT)
    target_link_libraries(shuttlesock PUBLIC ${CMAKE_THREAD_LIBS_INIT})
  endif()
endfunction()
